### ISSUE TITLE
sync GSM Client's TCP connection's time server with esp32's onboard clock

### ISSUE THREAD

**Issue by ejri** [khoih-prog/GSM_Generic#1]
**Is your feature request related to a problem? Please describe.**
`configTime` is a part of ESP32 core and relies on ESP32's own WiFI to be connected for it to work. When connecting over a GSM module, WiFi connections are not necessary, but that means that ESP32 can't use UDP on WiFi to sync with NTP, since wifi is not connected. Deepsleep or other time related modes wont work without onboard clock.

**Describe the solution you'd like**
Connect GSM Client's TCP connection to get the time from a TCP source (like the NIST daytime server) and then set the onboard clock manually based on the time returned.

**Describe alternatives you've considered**
using RTC module, isn't ideal
NTP AT command for the sim7000, in some cases, it may not be supported

**Additional context**
https://github.com/vshymanskyy/TinyGSM/issues/357
https://github.com/Azure/azure-iot-sdk-c/issues/1914
https://forum.arduino.cc/index.php?topic=88389.0
https://simcom.ee/documents/SIM7000E/SIM7000%20Series_AT%20Command%20Manual_V1.03.pdf

**Comment by khoih-prog** [comment]
This library is **not** supporting SIM7xxx now, only these [**Supported u-blox modems**](https://github.com/khoih-prog/GSM_Generic#supported-modems)

Moreover, did you try the [**GPRSUdpNtpClient**](https://github.com/khoih-prog/GSM_Generic/tree/main/examples/GPRSUdpNtpClient) if you're using ESP32 with u-blox modems?

**Comment by ejri** [comment]
Yeah, I saw the library and the sim7000 not being supported yet. Wanted to keep in mind to contribute or merge my workaround if I manage to work around it..

**Comment by khoih-prog** [comment]
Thanks. Your contribution is always welcome. Please post here if you have your working work-around.

**Comment by capedra** [comment]
I got it working on SIM800C, so, it may not be very difficult to adapt it to SIM7000:
https://github.com/vshymanskyy/TinyGSM/issues/357#issuecomment-973873741

**Comment by khoih-prog** [comment]
Hi @capedra 

Thanks for your solution which will help many other users.

Hi @ejri 

Could you try and post the result. I'm sorry I can't help as I don't have any SIM7000 to test.

Good Luck,

**Comment by ejri** [comment]
It wasn't really a work around. I connected to the cellular network first, then pulled the NTP from from the internet.  


This is a better example than what I have:


https://randomnerdtutorials.com/esp32-ntp-client-date-time-arduino-ide/
