### ISSUE TITLE
Add PEM to DER converter tool to get certificates in HEX format

### ISSUE THREAD

**Issue by msentuerk** [khoih-prog/GSM_Generic#3]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when searching for a toll and still searching.
I had the problem to convert existing PEM certificates (keys also) to DER format. Thanks there are online web tools for it but it gives it all the time in DER file format which is encrypted. So, I have the problem to get the DER certs in HEX specially in uint8_t format.

**Describe the solution you'd like**
Maybe there is a tool (I am also searching for it) which can convert PEM -> DER -> uint8_t

**Describe alternatives you've considered**
DER -> uint8_t

I hope this feature will be added. I am currently searching for this kind of tool. When I find one, I will test it and give a feedback to it.

**Comment by khoih-prog** [comment]
You can use **hexdump / xxd** command in Linux / Ubuntu to convert from DER binary format to ASCII uint8_t text format. Check [**xxd** command](https://helpmanual.io/help/xxd/)

```
xxd -i server.der > server_der.h
```

To convert from CRT to DER, have a look at [**openssl** command](https://www.openssl.org/docs/man1.0.2/man1/openssl.html) or [**openssl**](https://www.digicert.com/kb/ssl-support/openssl-quick-reference-guide.htm)

```
openssl x509 -in server.crt -outform der -out server.der
```

For Windoze, search for similar commands.

I'm closing this now as this has **nothing to do** with this library. I suggest you post on Arduino forum to ask for help / input and to have better help and reach to many more people.

Using SSL requires better knowledge, time and skills.

Good Luck,
