### ISSUE TITLE
 Add support for SIMCom LTE Module SIM7600E

### ISSUE THREAD

**Issue by A-n-d-y-K** [khoih-prog/GSM_Generic#6]
**Describe the solution you'd like**
Dear contributors of GSM_Generic Repository. Thanks for your effort on creating and maintaining it. May I ask for an extension to support  SIMCom LTE Module SIM7600E?
Many thanks in advance.

**Comment by khoih-prog** [comment]
Sorry. I currently don't have any **SIM7600xy** to test and won't add the support to that `SIMCom LTE Module SIM7600E` anytime in the near future.

Try to use the [**TinyGSM** Library](https://github.com/vshymanskyy/TinyGSM) which is supporting that SIM7600xy modules.

**Comment by A-n-d-y-K** [comment]
Hello @khoih-prog,
thanks for your fast reply. Sadly [TinyGSM Library](https://github.com/vshymanskyy/TinyGSM) does not support SSL for `SIMCom LTE Module SIM7600E` .
- Do you know a library which is supporting this?
- Is there a chance that you would extend this library with SSL for `SIMCom LTE Module SIM7600E` if you would have an SIM7660E module?

**Comment by khoih-prog** [comment]
> Sadly TinyGSM Library does not support SSL for SIMCom LTE Module SIM7600E .

TinyGSM is the best library to use. I don't know why SSL is not supported yet. You can open an enhancement request there to know why or **if SSL is actually supported by SIM7600xy design**. I haven't done any research on SIM7600xy to know yet.

> Do you know a library which is supporting this?

No. TinyGSM is the only and best one out there.

> Is there a chance that you would extend this library with SSL for SIMCom LTE Module SIM7600E if you would have an SIM7600E module?

It's possible with **SIM7600A**, but I can't be 100% sure about it until spending some time to code and test. Actually **SIM7600A** has to be used here in Canada / North America. AFAIK, **SIM7600E** is designed for Thailand/Korea, and some countries in Asia. I'm not sure if SIM7600E is compatible here in Canada.

Another option is that you can also modify the TinyGSM / GSM_Generic code and add SSL support and test there yourself.
